name: CI

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2

# for now disabled (need tor esolve https://github.com/Spotifyd/spotifyd/issues/659):
#      - name: Build code
#        run: cargo build --verbose
#
#      - name: Build examples
#        run: cargo build --examples --verbose
#
#      - name: Build tests
#        run: cargo build --tests --verbose
#
#      - name: Run tests
#        run: cargo test

  deploy-dev:
    runs-on: ubuntu-latest
    needs: ["build-and-test"]
    environment: dev
    steps:
      - name: Dummy deploy to dev
        run: |
          echo "deployed to dev!"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: ["deploy-dev"]
    environment: prod
    steps:
      - name: Dummy deploy to prod
        run: |
          echo "deployed to prod!"